// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnpYomtPKnWY5rd_F6d3ZJZyzArA4_kcU',
    appId: '1:815563245650:android:5cd4ac16bdb033a6b0378b',
    messagingSenderId: '815563245650',
    projectId: 'sambook-58156',
    storageBucket: 'sambook-58156.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2suyujaSUk48i8Voa26iIAi7JvKsl8TM',
    appId: '1:815563245650:ios:bffc6293d5a8f763b0378b',
    messagingSenderId: '815563245650',
    projectId: 'sambook-58156',
    storageBucket: 'sambook-58156.firebasestorage.app',
    androidClientId: '815563245650-qtaol1c2o83vu6adtf5fgeekjigej6sk.apps.googleusercontent.com',
    iosClientId: '815563245650-4gd8jpodg561bb0nif8gd55klrigmpg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.sambook',
  );
}
